### ISSUE TITLE
How different is Matrix from Surge?

### ISSUE THREAD

**Issue by rmzr7** [hollance/Matrix#1]
How different is Matrix from Surge?

**Comment by hollance** [comment]
It does many of the same things but the API is different.

I'm not sure Matrix actually still works with Swift 3. I'm also not using it anymore as I've switched to Python for doing machine learning. That said, if I _were_ to go back to Swift I'd probably rewrite this as a Tensor class instead of a matrix so it allows for n-dimensions instead of just 2.

**Comment by rmzr7** [comment]
That's fair! 

Thanks!
